services:
  postgres:
    container_name: postgres
    image: postgres:16.2-bullseye
    environment:
      - POSTGRES_PASSWORD=postgres
    user: root
    volumes:
      - postgres:/var/lib/postgresql/data/
    healthcheck:
      test: pg_isready -d postgres
      interval: 10s
      timeout: 3s
      retries: 3

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8.4
    user: root
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@domain.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
      - PGADMIN_CONFIG_SERVER_MODE=False
      - PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED=False
    ports:
      - 5050:80
    entrypoint: /bin/sh -c "chmod 600 /pgadmin4/postgres.pass; /entrypoint.sh"
    volumes:
      - ./infra/config/pgadmin/servers.json:/pgadmin4/servers.json
      - ./infra/config/pgadmin/postgres.pass:/pgadmin4/postgres.pass
    depends_on:
      - postgres

  # dashbaord:
  #   container_name: dashboard
  #   image: ghcr.io/nikolamilosa/dashboard:0.1.0
  #   ports:
  #     - 8080:8080
  #   environment:
  #     ConnectionStrings__DefaultConnection: "Host=postgres;Username=postgres;Password=postgres;Database=postgres"

volumes:
  postgres:
